---
title: "Amerika Birleşik Devletleri'ndeki toplu katliamların bir analizi: Modeller, eğilimler ve çıkarımlar."
author: 
  - Abed alsalam Anka[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 19080007, [Github Repo](https://github.com/abed-alsalam-anka/AraSinav)


# Giriş
Son yıllarda Amerika Birleşik Devletleri okullarda, işyerlerinde ve diğer yerlerde meydana gelen birçok toplu katliam yaşadı. Bu trajik olaylar, toplu katliam konusunda kamuoyunda endişeye yol açtı. Amerika Birleşik Devletleri'ndeki toplu katliam konusunu daha iyi anlamak için, 1982'den 2015'e kadar bu tür olayların bir veri setini inceleyerek bir analiz yapacağız. Data.world web sitesinden Mother Jones'un soruşturmasından aldığımız veri seti, yer, tarih, ölüm ve yaralanma sayısı, kullanılan silah türü, ve her olayın diğer özellikleri içerir. Verileri analiz ederek , kalıpları ve eğilimleri ve ayrıca sorunu çözmeye yardımcı olan politikalar için çıkarımları keşfetmeyi amaçlıyoruz. Analiz ayrıca veri setinin sınırlamalarını ve böylesine karmaşık bir konuyu incelemenin zorluklarını da inceler.


## Çalışmanın Amacı
Toplu katliamlar, Mağdurlar ve aileleri için yıkıcı sonuçlar doğuran ABD'de ciddi bir kamu güvenliği sorunu haline geldi. Mevcut verileri analiz ederek, bu olayların özellikleri hakkında fikir edinebiliriz.

Bu analizin asıl önemi, bunların oluşmasına katkıda bulunan faktörler hakkında içgörü kazanabilmemiz ve böylece politika yapıcıları toplu katliamlar neden olduğu zararı önleme ve hafifletme yolları hakkında bilgilendirebilmemizdir. Yıllara göre kazalardaki artışın boyutunu ve failin cinsiyeti, mağdur sayısı, önceki akıl hastalıklarının varlığı vb. gibi verilerde yer alan değişkenleri inceleyeceğimiz yer.

Ayrıca, bu analiz farkındalığı artırmaya ve toplu katliamlar hakkında kamuoyunu uyarmaya da yardımcı olabilir. Bu olgunun bir analizini yaparak, politika yapıcıları, medyayı ve halkı bu durumu ele almak için harekete geçmeye teşvik edebiliriz.



## Literatür 
2012 Sandy Hook İlköğretim Okulu'ndaki silahlı saldırı gibi trajik olayların ulusal dikkatleri üzerine çekmesiyle, toplu katliamlar ABD'de acil bir sorun haline geldi. toplu katliamlar çoğunlukla akıl hastalığı veya psikolojik sıkıntı geçmişi olan genç, beyaz erkekler tarafından gerçekleştiriliyor.[@metzl2021mental]

1966'dan 2012'ye kadar dünya çapındaki toplu katliamları belirlemeye yönelik bir çalışma, ABD'de kişi başına düşen toplu katliamlar, incelenen diğer tüm ülkelerden daha fazla olduğunu ortaya çıkardı [@lankford2016public]. Ayrıca, ABD'de son 20 yılda toplu silahlı saldırı olaylarının çoğu ticari veya eğitim amaçlı yerlerde meydana geldi ve erkek suçlular tarafından gerçekleştirildi [@schildkraut2018mass]. Bu, Beyaz üstünlük,toksik erkekliğin bunda oynadığı role ilişkin tartışmayı gündeme getirdi ve ayrıca okullarda ve aile ortamında zorbalık ve bunların bu konuda ne oynadığına dair tartışma yükseldi. Bazıları, Amerika'da silah bulma kolaylığının bu olayların ortaya çıkmasına katkıda bulunduğunu iddia ederken, diğerleri sorunun daha derin ve birden çok toplumsal boyutu olduğuna inanıyor.

Bazı toplu katillerin, iyi bilinen önceki katillerden ilham aldığını belirtmekte fayda var. Sadece önceki katillerle ilgili değiller, onlardan ilham alıyorlar ve onları geçmek istiyorlar. Bu, medyanın bu olayları haber yapma biçimine yönelik eleştirilere yol açtı. Medyanın bu olayları kapsaması, bir "bulaşma etkisine" katkıda bulunabilir; bu durumda, halihazırda şiddet eylemleri işleme riski taşıyan bireyler, önceki faillere gösterilen ilgiyle daha fazla motive olabilir [@murray2017mass; @krouse2015mass].

Genel olarak toplu katliamlar üzerine yapılan araştırmalar, bu trajik olaylara ve bunları önlemenin potansiyel yollarına ilişkin değerli içgörüler sağlamıştır. Bununla birlikte, toplu infazların en iyi nasıl tanımlanacağı ve ölçüleceği, bunların meydana gelmesine hangi faktörlerin katkıda bulunduğu ve bu tür olayların meydana gelmesini önlemek veya azaltmak için dikkate alınması gereken önleyici tedbirlerin neler olduğu konusunda hala çok fazla tartışma var.


\newpage
# Kaynakça {#references}
<div id="refs"></div>

